name: Test custom actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./test-terraform
      - uses: ./terraform-deploy
        with:
          terraform-command: plan
          terraform-directory: ./test-terraform

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./docker-build-push
        with:
          registry: docker.io
          image-name: test-app:latest
          push: false

  doc-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./doc-build-deploy
        with:
          doc-directory: "."
          doc-build-command: "mkdocs build"
          publish-directory: "./site"
          deploy: false
